# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-04 12:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0002_auto_20160404_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roster',
            name='doubles_partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tournaments.TeamPlayer'),
        ),
        migrations.AlterField(
            model_name='roster',
            name='player1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player1', to='tournaments.TeamPlayer'),
        ),
        migrations.AlterField(
            model_name='roster',
            name='player2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player2', to='tournaments.TeamPlayer'),
        ),
        migrations.AlterField(
            model_name='roster',
            name='player3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player3', to='tournaments.TeamPlayer'),
        ),
        migrations.AlterField(
            model_name='roster',
            name='player4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player4', to='tournaments.TeamPlayer'),
        ),
    ]
